import type { AdminReview } from "@/shared/types";

export const adminReviewsList: AdminReview[] = [
  {
    id: 1,
    customer: "Trần Minh Khoa",
    provider: "Nguyễn Văn An",
    service: "Sửa điện",
    rating: 5,
    comment: "Thợ chuyên nghiệp, đúng giờ, sạch sẽ!",
    date: "20/06/2026",
    status: "published",
  },
  {
    id: 2,
    customer: "Nguyễn Thị Lan",
    provider: "Phạm Hoa",
    service: "Dọn dẹp",
    rating: 4,
    comment: "Dịch vụ tốt, giá hợp lý.",
    date: "18/06/2026",
    status: "published",
  },
  {
    id: 3,
    customer: "Lê Văn Phúc",
    provider: "Trần Thị Bình",
    service: "Thông cống",
    rating: 2,
    comment: "Đến muộn 30 phút, không báo trước. Rất thất vọng.",
    date: "15/06/2026",
    status: "flagged",
  },
  {
    id: 4,
    customer: "Phạm Thị Hương",
    provider: "Lê Minh Cường",
    service: "Điều hòa",
    rating: 5,
    comment: "Rất hài lòng! Sẽ đặt lại.",
    date: "10/06/2026",
    status: "published",
  },
  {
    id: 5,
    customer: "Hoàng Văn Đức",
    provider: "Vũ Quốc Tuấn",
    service: "Sửa thiết bị",
    rating: 1,
    comment: "Tệ! Sửa xong còn hỏng hơn trước.",
    date: "08/06/2026",
    status: "flagged",
  },
];
