import type { AdminService, AdminServiceType } from "@/shared/types";

export const adminServicesList: AdminService[] = [
  {
    id: 1,
    name: "Sửa điện dân dụng",
    type: "Điện",
    price: "150,000",
    providers: 45,
    orders: 312,
    status: "active",
  },
  {
    id: 2,
    name: "Thay bóng đèn & ổ cắm",
    type: "Điện",
    price: "80,000",
    providers: 38,
    orders: 198,
    status: "active",
  },
  {
    id: 3,
    name: "Thông cống tắc",
    type: "Nước – Ống",
    price: "120,000",
    providers: 32,
    orders: 245,
    status: "active",
  },
  {
    id: 4,
    name: "Sửa máy lạnh",
    type: "Điều hòa",
    price: "200,000",
    providers: 28,
    orders: 156,
    status: "active",
  },
  {
    id: 5,
    name: "Dọn dẹp nhà cơ bản",
    type: "Dọn dẹp",
    price: "80,000",
    providers: 51,
    orders: 421,
    status: "active",
  },
  {
    id: 6,
    name: "Sơn tường nội thất",
    type: "Sơn",
    price: "300,000",
    providers: 18,
    orders: 89,
    status: "inactive",
  },
  {
    id: 7,
    name: "Sửa tủ lạnh",
    type: "Thiết bị",
    price: "180,000",
    providers: 29,
    orders: 134,
    status: "active",
  },
];

export const adminServiceTypesList: AdminServiceType[] = [
  { id: 1, name: "Điện", icon: "⚡", services: 8, providers: 45, orders: 312, active: true },
  { id: 2, name: "Nước – Ống", icon: "💧", services: 6, providers: 32, orders: 245, active: true },
  { id: 3, name: "Điều hòa", icon: "❄️", services: 5, providers: 28, orders: 198, active: true },
  { id: 4, name: "Dọn dẹp", icon: "🧹", services: 4, providers: 51, orders: 421, active: true },
  { id: 5, name: "Sơn", icon: "🎨", services: 3, providers: 18, orders: 89, active: false },
  { id: 6, name: "Thiết bị", icon: "🔧", services: 7, providers: 29, orders: 156, active: true },
];
